# Generated by Django 4.1.1 on 2022-09-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='student', through='school.StudTeach', to='school.teacher'),
        ),
    ]
