# Generated by Django 4.1.1 on 2022-09-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_student_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studteach',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='school.student'),
        ),
        migrations.AlterField(
            model_name='studteach',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='school.teacher'),
        ),
    ]
