# Generated by Django 4.1.1 on 2022-09-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_student_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
