# Generated by Django 4.1.1 on 2022-09-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_rename_teacher_student_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studteach',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qwe', to='school.student'),
        ),
        migrations.AlterField(
            model_name='studteach',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qwe', to='school.teacher'),
        ),
    ]
