# Generated by Django 4.1.1 on 2022-09-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_student_teachers_alter_studteach_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teachers',
            field=models.ManyToManyField(related_name='students', through='school.StudTeach', to='school.student'),
        ),
    ]
